# Header
menu:
  Home: /
  Archives: /archives
  Recruiting: http://www.coupang.com/np/jobs
  Github:
    url: https://github.com/Coupang-Tech
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Home

# URL of the Home page image
index_cover: /img/home-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: Coupang-Tech
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/coupang
twitter_handle:
facebook_url: https://www.facebook.com/coupang.recruit
github_url: https://github.com/Coupang-Tech
gitlab_url:
linkedin_url: https://www.linkedin.com/jobs/search?f_C=2824374&locationType=Y
mailto: recruit@coupang.com
